<?xml version="1.0" encoding="utf-8"?><Database Name="Students" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-KQTR1T6;Initial Catalog=Students;Integrated Security=True" SettingsObjectName="WindowsFormsApp1.Properties.Settings" SettingsPropertyName="StudentsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.StudentList" Member="StudentList">
    <Type Name="StudentList">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Surname" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Subject" Member="Subject">
    <Type Name="Subject">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="NumberOfHours" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Teacher" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
    </Type>
  </Table>
</Database>